// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btxfdlbseaxcdihdnvqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0eGZkbGJzZWF4Y2RpaGRudnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4Mzk3OTcsImV4cCI6MjA1MTQxNTc5N30.vArE-7h4JxUI2h5OZs6nbQJszZQXlWYggmgE0GCLZvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);